"""
Django settings for ProyectoSaaS project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET KEY (Leer desde entorno y forzar error si no está)
SECRET_KEY = os.environ.get('SECRET_KEY')

if not SECRET_KEY:
    # Si la variable de entorno no existe, Django falla al arrancar.
    # En desarrollo local, puedes usar un archivo .env o configurarla manualmente.
    raise ValueError("La variable de entorno SECRET_KEY es obligatoria para la seguridad.")

# DEBUG (Desactivar en Producción)
# Leemos el valor de la variable de entorno, por defecto es False si no se encuentra.
DEBUG = os.environ.get('DEBUG') == 'True'

# ALLOWED_HOSTS (URLs del servidor)
# En producción, esto DEBE incluir los dominios/IPs de AWS (EC2/Elastic Beanstalk).
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') 
if DEBUG:
    ALLOWED_HOSTS += [] # Añade hosts de prueba si DEBUG es True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProyectoSaaS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectoSaaS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB_NAME', 'ProyectoSaaS'), # Nombre de la DB
        'USER': os.environ.get('POSTGRES_USER'),                    # Usuario Master de RDS
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),            # Contraseña
        'HOST': os.environ.get('POSTGRES_HOST'),                    # Endpoint de AWS RDS (ej: mi-db.xyz.us-east-1.rds.amazonaws.com)
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),            # Puerto por defecto de PostgreSQL
        'CONN_MAX_AGE': 600,                                        # Opcional, mejora el rendimiento de conexión
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Ruta donde Django buscará tus archivos propios (CSS, JS, etc.)
STATICFILES_DIRS = [
    BASE_DIR / 'static',   # crea esta carpeta junto a manage.py
]

# Ruta donde se almacenarán todos los archivos estáticos recolectados
STATIC_ROOT = BASE_DIR / 'staticfiles'  # se genera automáticamente al usar collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Indicar que usara CustomUser como modelo para usuario
AUTH_USER_MODEL='portal.CustomUser'

#Comportamiento login

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

from django.urls import reverse_lazy

LOGIN_REDIRECT_URL = reverse_lazy('app')
LOGIN_URL = reverse_lazy('login')
LOGOUT_REDIRECT_URL = reverse_lazy('login')

# settings.py

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',  # Cambia a INFO si no quieres tanto detalle
    },
}
